/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package party;


import java.sql.*;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
/**
 *
 * @author homek
 */
public class Kullanicigirisi extends javax.swing.JFrame {
    Connection con;
    PreparedStatement preparedStatement = null;
    int userID;

    
    public Kullanicigirisi() {
        try{
            Class.forName("org.postgresql.Driver");
            con = DriverManager.getConnection("jdbc:postgresql://localhost:5432/Party", "postgres", "123456");
          
            System.out.println("Baglanti basarili");
            
        }
            catch(Exception e){
                System.out.println(e.getMessage());
            }
        
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        userIDtf = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        girisparolatf = new javax.swing.JTextField();
        girisyapbutton = new javax.swing.JButton();
        kayitolbutton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("User ID:");

        userIDtf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                userIDtfActionPerformed(evt);
            }
        });

        jLabel2.setText("Parola");

        girisyapbutton.setText("Giriş Yap");
        girisyapbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                girisyapbuttonActionPerformed(evt);
            }
        });

        kayitolbutton.setText("Kayıt Oluştur");
        kayitolbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kayitolbuttonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(86, 86, 86)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(userIDtf, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(kayitolbutton)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(girisyapbutton, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(girisparolatf)))))
                .addContainerGap(53, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(73, 73, 73)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(userIDtf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(girisparolatf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(girisyapbutton)
                .addGap(18, 18, 18)
                .addComponent(kayitolbutton)
                .addContainerGap(95, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void userIDtfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_userIDtfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_userIDtfActionPerformed

    private void girisyapbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_girisyapbuttonActionPerformed
     userID = Integer.valueOf( userIDtf.getText() );
    String parola = girisparolatf.getText();
    
    try{
           
           String sorgu = "select * from kullanici where userid = ? and parola = ? ";
               preparedStatement = con.prepareStatement(sorgu);
               preparedStatement.setInt(1, userID);
               preparedStatement.setString(2, parola);
                
                ResultSet rs = preparedStatement.executeQuery();
                
            if (rs.next()){
                userID = rs.getInt("userid");
                setVisible(false);
                UserInterface us = new UserInterface(userID);
                us.setVisible(true);
            }
            else{
                JOptionPane.showMessageDialog(null,"Hatalı mail adresi veya parola");
                return;
            }
                
            
        }
            catch(Exception e){
                System.out.println(e.getMessage());
            }
    }//GEN-LAST:event_girisyapbuttonActionPerformed

    private void kayitolbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kayitolbuttonActionPerformed
               setVisible(false);
               MusteriKaydi musteriKayit = new MusteriKaydi();
               musteriKayit.setVisible(true);
               
        
    }//GEN-LAST:event_kayitolbuttonActionPerformed
    public int getUserID() {
        return userID;
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Kullanicigirisi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Kullanicigirisi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Kullanicigirisi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Kullanicigirisi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Kullanicigirisi().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField girisparolatf;
    private javax.swing.JButton girisyapbutton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JButton kayitolbutton;
    private javax.swing.JTextField userIDtf;
    // End of variables declaration//GEN-END:variables
}
